### ISSUE TITLE
 88 LOC Version speed difference

### ISSUE THREAD

**Issue by Schizo** [yuanming-hu/taichi_mpm#10]
First of all thanks for creating this separate repo, I was  able to successfully build both the examples and the  88 LOC Version on latest Ubuntu. I was wondering if there was a difference in terms of speed between the 88 LOC version and the full? I just realized that when I was running the 88 LOC, only 1 cpu was used.

**Comment by yuanming-hu** [comment]
The 88 LOC version is very slow compared to the full version. However since it is 2D and there are very few particles so it's still real-time.
