### ISSUE TITLE
Command ti install mpm errors

### ISSUE THREAD

**Issue by af654** [yuanming-hu/taichi_mpm#11]
I was following the instructions to install the High-Performance 3D Solver however the make file for the command ti install mpm failed. I am running on a bash terminal window for a 2018 Macbook Pro.
Output:
make[1]: *** [projects/mpm/CMakeFiles/taichi_mpm.dir/all] Error 2
make: *** [all] Error 2
  Error: Build failed.

The errors that I get are:
error: cannot initialize a variable of type 'char *' with an rvalue of type 'int'
error: static_assert failed due to requirement 'bit::is_power_of_two((int)sizeof(GridState<3>))'
error: no matching function for call to 'equal'
error: no member named 'block_zbits' in 'SPGrid::SPGrid_Mask<6, 6, 2, 12>'

These errors begin at build percentage 93%.
I installed taichi following the instructions in https://taichi.readthedocs.io/en/latest/installation.html
and I have all of the correct dependencies and versions of gcc and python.

Please let me know if I am missing something. Any feedback appreciated. 

<img width="1012" alt="screen shot 2019-03-07 at 11 42 11 am" src="https://user-images.githubusercontent.com/22079984/53973133-29309080-40ce-11e9-8265-b134775b3a09.png">

**Comment by yuanming-hu** [comment]
Hello, the software still needs a bit more work to run on Mac. Do you have a Linux machine available? Everything should be fine on Ubuntu 16.04/18.04

**Comment by af654** [comment]
Hi Yuanming,
Yes I was able to get the example scripts to run in Ubuntu 16.04. Thank you.
Last question, is there a built in way to visualize the frames or do I have to install Houdini specifically and not Blender/Maya?

**Comment by yuanming-hu** [comment]
Good to know that it runs on Ubuntu.

Unfortunately, Houdini is needed right now. However, we do plan to make such a viewer to view the results.

**Comment by yuanming-hu** [comment]
Merged into #12
