### ISSUE TITLE
plasticity

### ISSUE THREAD

**Issue by iammalekI** [yuanming-hu/taichi_mpm#15]
hello 
In the case of the snow related plasticity, I encountered the problem of 1 - tetac and 1 + tetas because I wanted to see how it was obtained for the soil of these values (although the empirical values do independ on the hydrostatic stress).

**Comment by yuanming-hu** [comment]
what does "1 - tetac and 1 + tetas" mean?

**Comment by iammalekI** [comment]
sig[i][i] = clamp(sig[i][i], 1.0f - 2.5e-2f, 1.0f + 7.5e-3f);
1 - tetac=1.0f - 2.5e-2f
1 + tetas =1.0f + 7.5e-3f

**Comment by yuanming-hu** [comment]
I see. I think those are arbitrary values tuned for visual effects. For engineering applications, you should definitely use a more well-founded constitutive model.

**Comment by iammalekI** [comment]
relate
https://github.com/yuanming-hu/taichi_mpm/blob/master/mls-mpm88-explained.cpp

**Comment by iammalekI** [comment]
Are computational values accurate or approximate?
Example: deformation  gradient  and velocity.

**Comment by yuanming-hu** [comment]
They are approximate due to discretization errors...MLS-MPM is first-order accurate.

**Comment by iammalekI** [comment]
thanks
