### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by yuanming-hu** [yuanming-hu/taichi_mpm#2]

**Comment by ruby0x1** [comment]
This work looks really compelling but unfortunately a GPL (or other viral license) likely means the code implementation can never see wide spread use :( even looking at the repo has a risk associated (see https://en.wikipedia.org/wiki/Clean_room_design in the context of GPL and the consequence of it) and most/all companies cannot take that risk.

I hope that the license decisions took that into account!

**Comment by yuanming-hu** [comment]
We have switched the license to MIT. Thanks for the suggestions.
