### ISSUE TITLE
error: static assertion failed:

### ISSUE THREAD

**Issue by yaolyu** [yuanming-hu/taichi_mpm#4]
Hi Yuanming,
When I installed mpm solver project using command'ti install mpm', several errors appear a lot of times which I think maybe you could help me to solve. Errors are :
/taichi/projects/mpm/src/mpm_fwd.h:116:1: error: static assertion failed: GridState<2> size must be POT
 static_assert(bit::is_power_of_two(sizeof(GridState<2>)),
error: ‘using Vector = struct taichi::VectorND<3, float, (taichi::InstSetExt)0> {aka struct taichi::VectorND<3, float, (taichi::InstSetExt)0>}’ has no member named ‘v’
         p.pos.v = _mm_fmadd_ps(v_, delta_t_vec, p.pos.v);
               ^
Could you please help me have a look at these problems?

**Comment by yuanming-hu** [comment]
Thanks for your questions.

Could you let me know your CPU model?

**Comment by yaolyu** [comment]
CPU information is :
model		: 45
model name	: Intel(R) Xeon(R) CPU E5-1650 0 @ 3.20GHz

**Comment by yuanming-hu** [comment]
The CPU is 6-year old and I need some time to support it...A quick "fix" is to run it on a computer with Haswell (released 2013) or later CPUs.

**Comment by yaolyu** [comment]
Let me try! Thank you!
