### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by blazecus** [yuanming-hu/taichi_mpm#46]
Trying to install the legacy version, but keep getting this when running install.py. 

/home/blazes/taichi/include/taichi/math/linalg.h:372:11: warning: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘struct taichi::VectorND<4, float, taichi::InstSetExt::AVX2>’ with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
  372 |     memcpy(this, &o, sizeof(*this));
      |     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
/home/blazes/taichi/include/taichi/math/linalg.h:154:8: note: ‘struct taichi::VectorND<4, float, taichi::InstSetExt::AVX2>’ declared here
  154 | struct VectorND : public VectorNDBase<dim__, T, ISE> {
      |        ^~~~~~~~
make[2]: *** [CMakeFiles/taichi_core.dir/build.make:141: CMakeFiles/taichi_core.dir/include/taichi/dynamics/rigid_body.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:96: CMakeFiles/taichi_core.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
  Error: Build failed.
  Error: installation failed.

**Comment by tasbolat1** [comment]
Hi @blazecus,
Did u solve this problem?

**Comment by ComicAddict** [comment]
Hi @blazecus  and @tasbolat1 I am  getting this issue on Linux as well, do you have any solutions to this issue?
