### ISSUE TITLE
Why is memory usage increasing?

### ISSUE THREAD

**Issue by haeriamin** [yuanming-hu/taichi_mpm#7]
Hi, thank you for this amazing tool. I'd like to know why memory usage increases during the run of an example with 2m particles and it's killed at second 3 of the simulation; ty.

![screen shot 2018-11-08 at 02 07 36](https://user-images.githubusercontent.com/44217824/48182975-2f1e8c80-e2fb-11e8-9c20-5894b5a6135b.png)

**Comment by yuanming-hu** [comment]
Thanks for the feedback! We haven't run this code on a machine with < 32 GB memory. One possibility is that SPGrid does not release the touched blocks. I will take a look when I have a chance.
