### ISSUE TITLE
Particles leaking from rigid bodies

### ISSUE THREAD

**Issue by haeriamin** [yuanming-hu/taichi_mpm#8]
Hi. I wanted to make sure that I'm using a correct grid spacing (dx=dimension/resolution) and/or pd's minimum distance. In the following pics (3D and top views) the setting is as default. However, I'm seeing some leakages from the top rigid surface. Please let me know if there is sth that I can figure it out; ty.

![3dview](https://user-images.githubusercontent.com/44217824/48227465-6b400480-e370-11e8-9c41-a7a81031d551.png)
![topview](https://user-images.githubusercontent.com/44217824/48227466-6b400480-e370-11e8-996f-450dd9fb58be.png)

**Comment by yuanming-hu** [comment]
Hi,

Thanks for trying! Does the leakage happen at the surface or corner?

**Comment by yuanming-hu** [comment]
and the blue arrows are?

**Comment by haeriamin** [comment]
Thank you for your response. The leakage at the corner is my fault, as there is a gap there; but there is still leakages from the top surface and I'm not sure why. Should I define level set instead of rigid body, like you did in sand_stir model? The blue arrows show the velocity vector in Houdini.

**Comment by yuanming-hu** [comment]
Resolved by setting `penalty=1e4`
